language: python

python:
- '3.7'

postgres:
  adapter: postgresql
  database: contax
  username: contax

before_install:
- pip install poetry
- psql -c 'create database contax;' -U postgres

install:
- poetry install -v

script:
  - pytest contax/backend
